databases:
  - name: websitejudge
    plan: free
    databaseName: websitejudge
    user: websitejudge

services:
  - type: web
    plan: free
    name: websitejudge
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: websitejudge
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
